---
language: ruby
rvm:
  - rbx
env:
  - PACKER_VERSION="0.10.1"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y wget unzip
script:
  - sudo mkdir /opt/packer
  - pushd /opt/packer
  - echo "Downloading packer ${PACKER_VERSION}..."
  - sudo wget --no-verbose https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
  - echo "Installing packer ${PACKER_VERSION}..."
  - sudo unzip packer_${PACKER_VERSION}_linux_amd64.zip
  - sudo rm packer_${PACKER_VERSION}_linux_amd64.zip
  - pushd /usr/bin
  - "sudo ln -s /opt/packer/* ."
  - cd ${TRAVIS_BUILD_DIR}
  - packer push wily64-developer-environment.json
