---
  - name: Install docker-compose via curl
    shell: curl -L https://github.com/docker/compose/releases/download/1.10.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
      creates=/usr/local/bin/docker-compose

  - name: Make docker-compose executable
    file:
      path=/usr/local/bin/docker-compose
      mode="a+x"
