---
  - name: create intelli directory
    file:
      path=/opt/intellij/{{ intellij_version }}/
      state=directory
      mode=0777

  - name: download the file
    get_url:
      url="https://download.jetbrains.com/idea/ideaIC-{{ intellij_version }}-no-jdk.tar.gz"
      dest="/opt/intellij/"
      checksum="sha256:{{intellij_sha256_checksum}}"

  - name: untar
    unarchive:
      src: "/opt/intellij/ideaIC-{{ intellij_version }}-no-jdk.tar.gz"
      dest: "/opt/intellij/{{ intellij_version }}"
      extra_opts: [--strip-components=1]

  - name: update directory permissions
    file:
      path=/opt/intellij/
      state=directory
      owner=vagrant
      group=vagrant
      recurse=yes

  - name: add symlink
    file:
      src="/opt/intellij/{{ intellij_version }}/bin/idea.sh"
      dest="/usr/bin/intellij"
      state=link

  - name: upload icon file
    copy:
      src={{ item.src }}
      dest={{ item.dest }}
    with_items:
    - { src: 'jetbrains-idea-ce.desktop', dest: '/tmp/jetbrains-idea-ce.desktop' }

  - name: update icon file
    replace:
      dest=/tmp/jetbrains-idea-ce.desktop
      regexp='^(.*)REPLACE_INTELLIJ_PATH(.*)$'
      replace='\1/opt/intellij/{{ intellij_version }}\2'

  - name: ensure desktop shortcut directory exists
    file:
      path=/usr/share/desktop-directories/
      state=directory
      mode=0755
    become: true

  - name: set intellij icon
    shell: xdg-desktop-menu install --novendor /tmp/jetbrains-idea-ce.desktop
    become: true

  - name: remove binaries
    file:
      path=/opt/intellij/ideaIC-{{ intellij_version }}-no-jdk.tar.gz
      state=absent
