---
- hosts: all
  vars:
    cf_cli_version: "6.29.0"
    maven_version: "3.5.0"
    maven_checksum: "35c39251d2af99b6624d40d801f6ff02"
    sbt_version: "0.13.15"
    intellij_version: "2017.2"
    intellij_sha256_checksum: "d88257b17447398ed60e7d774803cbc21e0fe7750add09622a98b936f14cd91f"
    sts_version: "3.9.0"
    eclipse_version: "4.7.0"
    docker_compose_version: "1.14.0"
    atom_version: "1.18.0"
    gradle_version: "4.0.1"
    go_version: "1.8.3"
    go_sha256_checksum: "1862f4c3d3907e59b04a757cfda0ea7aa9ef39274af99a784f5be843c80c6772"
    compliance_masonry_version: "1.1.2"
    bosh_cli_version: "2.0.28"
    bosh_cli_sha1_checksum: "7b7629fcdf8839cf29bf25d97e8ea6beb3b9a7b2"
    yaml_linux_version: "1.11"
    terraform_version: "0.9.11"
    bosh_bootloader_version: "3.2.6"
    postman_version: "5.1.2"
    postman_sha1_checksum: "59F1E93055159823146EBF1F50F8FAD384FCE5FE"
  gather_facts: yes
  become: yes
  roles:
    - disable_auto_update
    - developer_packages
    - atom
    - docker_service
    - docker_compose
    - cf_cli
    - maven
    - sbt
    - gradle
    - intellij
    - sts
    - unity_desktop
    - go
    - postman
    - gitbook
    - compliance_masonry
    - gcloud
    - newrelic
    - bosh
