---
- hosts: all
  vars:
    cf_cli_version: "6.26.0"
    maven_version: "3.5.0"
    maven_checksum: "35c39251d2af99b6624d40d801f6ff02"
    sbt_version: "0.13.15"
    intellij_version: "2017.1.3"
    intellij_sha256_checksum: "16ed4382b6e325d5aea6b2b3c46ef5d8b4b716bb24891933a2449a595a4724cd"
    sts_version: "3.8.4"
    eclipse_version: "4.6.3"
    docker_compose_version: "1.13.0"
    atom_version: "1.17.0"
    gradle_version: "3.5"
    go_version: "1.8.1"
    go_sha256_checksum: "a579ab19d5237e263254f1eac5352efcf1d70b9dacadb6d6bb12b0911ede8994"
    compliance_masonry_version: "1.1.2"
    bosh_cli_version: "2.0.16"
    yaml_linux_version: "1.10"
    terraform_version: "0.9.6"
    bosh_bootloader_version: "3.2.3"
  gather_facts: yes
  become: yes
  roles:
    - disable_auto_update
    - developer_packages
    - atom
    - docker_service
    - docker_compose
    - cf_cli
    - maven
    - sbt
    - gradle
    - intellij
    - sts
    - unity_desktop
    - go
    - postman
    - gitbook
    - compliance_masonry
    - gcloud
    - newrelic
    - bosh
