---
- hosts: all
  vars:
    cf_cli_version: "6.35.2"
    maven_version: "3.5.3"
    intellij_version: "2018.1"
    sts_version: "3.9.3"
    eclipse_version: "4.7.3"
    docker_compose_version: "1.20.1"
    atom_version: "1.20.1"
    gradle_version: "4.6"
    go_version: "1.10.1"
    compliance_masonry_version: "1.1.2"
    bosh_cli_version: "2.0.48"
    yq_linux_version: "1.14.0"
    terraform_version: "0.11.5"
    bosh_bootloader_version: "5.11.6"
    postman_version: "6.0.10"
    fly_version: "3.10.0"
    groovy_version: "2.4.13"
  gather_facts: yes
  become: yes
  roles:
    - disable_auto_update
    - developer_packages
    - git
    - atom
    - docker_service
    - docker_compose
    - cf_cli
    - maven
    - gradle
    - intellij
    - sts
    - unity_desktop
    - go
    - postman
    - gitbook
    - compliance_masonry
    - gcloud
    - newrelic
    - bosh
    - fly
    - groovy
    - taurus
    - json2yaml
